language:
  - cpp

before_install:
  #- pip install --user cpp-coveralls
  #- sudo apt-get update && sudo apt install libqt5widgets5 qtbase5-dev qt5-default -y
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
 - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "brontik-github"
    token:
      secure: $SONAR_TOKEN

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false
